### PR TITLE
Add fixes and improvements to seravo-plugin Updates, Reports and Logs pages

### PR DESCRIPTION
**Pull request by mvierma**
Add more information under Site Information on Reports page per issue #318 in another repo.

Site Info now shows the current Account Manager of the site if one is set and displays a message about account manager being a part of the Seravo Enterprise plan otherwise. Site info now also shows the emails of technical contacts of the site and links to the Updates page where user can add or remove technical contacts from their site.

Site Information postbox with new content:
image

This PR also adds the notification on failed full updates of the site on the Updates page if the full update hasn't been succesful in 30 days or over, as suggested in the issue #73. The notification shows lines from the latest update.log starting with "Updates failed!" to the user and prompts them to have a site developer take a look at the issue preventing the full update. The notification also links to the update log on the Logs page.

Preview of the notification:
image

Logs page now checks which .log files were found and if any are missing, the latest timestamped log file is fetched instead. This ensures that the page always has a logfile to show for every log type.

Example of the view with update.log file missing:
image

Lastly this also fixes the incorrect add_submenu_page calls on all modules and fixes the postbox placements where applicable per issue #228

### CODE REVIEW

**Comment by ottok** [comment]
Well done! 

Quickly skimmed through code.
- in commit 2c6039f120a41ad1e5321dff6d93f5b9ec57925e you add function `print_items()` - maybe you could extend the existing `print_item()` instead to keep the code simpler?
- in commit ccab71ca48353063c8352c0ab472270d09ad83d4 you change the previous commit - it is easier to review new code if you just squash all of the same commits to one step compared to master. Or is there something particular in the intermediate results that you want me to review instead of going directly for the end result this PR produces?
- in commit 91a9a2d4af72744883cab325acdf20611cbd3534 you add long A tags into the string that is to be translated, but there is really nothing to translate in the link syntax. Instead what link A stuff could be in the parameter and the string just keep the `see %2$s and %3$s.` as it was

**Comment by ottok** [comment]
Please squash and rebase on master. Consult @l3ku on PR principles.

**Comment by mvierma** [comment]
Commits should now be better organized and squashed so that each commit is it's own addition or fix.

**Comment by ottok** [comment]
End result looks good!

At least the first and last commit should be squashed. A pull request should  be a suggestion on how to change the master branch for better – it should not have commits that fix earlier commits in the same pull request.

Consult @l3ku on PR principles.

**Comment by l3ku** [comment]
We already discussed about how the PR should not have commits that alter something that was added in the same PR, but rather "get it right" in the first commit so that it is not necessary to alter the content in a later commit.

**Pull request merged**
