### PR TITLE
Update phpcs.xml configuration

### PR DESCRIPTION
**Pull request by l3ku**
#### What are the main changes in this PR?
Add some improvements to the PHPCS configuration file `phpcs.xml` and fix the new errors caused by the modifications.

##### Why are we doing this? Any context or related work?
I am currently writing a blog article about our PHP code style and linking this repo there, so the ruleset should be aligned with the written blog content.

See also https://github.com/Seravo/seravo-plugin/issues/258.

#### Where should a reviewer start?
Check the added rules whether they make sense, and then skim through the codebase changes to look for potential regressions in functionality caused by the fixes.

#### Manual testing steps?
Probably not necessary.

#### Screenshots
Nope.

### CODE REVIEW

**Comment by l3ku** [comment]
For more PHPCS customizable sniff properties, see:
- https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties
- https://github.com/WordPress/WordPress-Coding-Standards/wiki/Customizable-sniff-properties

To see which sniffs report what messages in the results, run `phpcs -s`.

**Comment by l3ku** [comment]
> Does @JoosuaKoskinen or @cr0vy have code style opinions here on what the ideal phpcs.xml enforces?

**Comment by JoosuaKoskinen** [comment]
I got no improvement ideas, this looks good to me too!

**Comment by l3ku** [comment]
I have now sort of self-reviewed this and made the following changes:
- Added `Generic.WhiteSpace.ArbitraryParenthesesSpacing` so that 0 spaces are used for arbitrary parentheses like `if ( ($a && $b) || $c ) ...` instead of  `if ( ( $a && $b ) || $c ) ...`
- Removed the excludes `PEAR.Functions.FunctionCallSignature` so that we can set a function call signature of `some_func($param1, $param2)` instead of `some_func( $param1, $param2 )`
- Excluded `WordPress.WhiteSpace.CastStructureSpacing.NoSpaceBeforeOpenParenthesis` and `WordPress.WhiteSpace.OperatorSpacing.NoSpaceBefore` because it conflicted with the above rule when using arbitrary parentheses

Also fixed the resulting errors with PHPCBF. I believe this ruleset is now well aligned with the blog post to be published soon.

**Comment by l3ku** [comment]
Reviewing the WPCS rulesets has also proven to be useful when determining what we want to exclude from them:
- https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress-Core/ruleset.xml
- https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress-Extra/ruleset.xml

**Comment by l3ku** [comment]
Also proceeded to update WPCS to a more recent version because it started giving me errors that were not present locally when testing on a more recent version on my local machine.

**Comment by ottok** [comment]
No new comments here for a while, so I assume it can be merged, right?

**Pull request merged**
