### PR TITLE
Forward 'Site Error Count logs'-link to 'php-error.log' and change login notification

### PR DESCRIPTION
**Pull request by VeetiYliHemmo**

### CODE REVIEW

**Comment by ottok** [comment]
The change you suggest is correct, well done!

While at it, can you come up with other ways to improve the contents of `function display_admin_errors_notification(`?

How about also styling the login notification and how the last login date is displayed?

**Comment by VeetiYliHemmo** [comment]
VIM bugged out. I'll remove those shortly.

**Comment by VeetiYliHemmo** [comment]
The change will make it so that the login notification will use the users firstname if possible. It'll also make the datetime easier to read.

**Comment by ottok** [comment]
Please run:
```
git remote add upstream https://github.com/Seravo/seravo-plugin.git # now your git (and gitk) sees both your fork and the original upstream
git checkout master
git pull upstream master # now your local master matches upstream master
git checkout feature/login-notification-direct-php-error-log-link
git rebase -i master
git push -f # this syncs your local git to your github fork repo
```

PIng also @JoosuaKoskinen

**Pull request merged**
