### PR TITLE
Add mail forwards table

### PR DESCRIPTION
**Pull request by JoosuaKoskinen**
## What are the main changes in this PR?

Adds mail forwards table to mails postbox on domains page.

The actions available are:
- Fetch forwards for a domain
- Create a new forward for a domain
- Delete a source and its destinations
- Modify the destinations of a source
- Modify the source

##### Why are we doing this? Any context or related work?

Closes: #13 

#### Where should a reviewer start?

These actions must be tested with a domain under Seravo's management.

#### Screenshots
After fetch:
mails-postbox-1
Editing:
mails-postbox-2

### CODE REVIEW

**Comment by elguitar** [comment]
CI fails with PHP<=7.2. Weird :raised_eyebrow: 
```
PHP Parse error:  syntax error, unexpected ')' in ./lib/domain-tables.php on line 367
```

Is there some 7.4 specific syntax or something?

I will proceed with the review regardless of this :)

**Comment by JoosuaKoskinen** [comment]
> Is there some 7.4 specific syntax or something?
There indeed was

**Comment by JoosuaKoskinen** [comment]
> When modifying, If I press `return`, it doesn't change to a new line. Why is that? However, it does work and the end result is parsed correctly.

I can't reproduce this. All the empty lines are removed when submitting the form. Maybe it submits the form somehow when you press `return`.

> When I save the forwards for a source, I think that it should show me all the forwards instead of staying in the empty "create" state.

That's because a lot of different sources are often needed. This way saving them is a lot faster. Do you think that should be changed?

**Comment by elguitar** [comment]
I PM'd you a video clip about what I ment with the return thing.

>That's because a lot of different sources are often needed. This way saving them is a lot faster. Do you think that should be changed?

Your reasoning seems valid. Let's leave it be and wait for feedback.

**Comment by JoosuaKoskinen** [comment]
The return thing only happened on Firefox. Fixed now!

**Comment by JoosuaKoskinen** [comment]
Found a couple of bugs, will change back to WIP

**Comment by JoosuaKoskinen** [comment]
All good now, can you review again @elguitar?

**Pull request merged**
