### PR TITLE
Fix dashicon align inside buttons (Closes: #386)

### PR DESCRIPTION
**Pull request by sjaks**
Set the vertical align of dashicon icons to middle so that they are inline with button text.

Now all buttons with icons are like the one at the bottom. Other ones are examples of the previous look.
Screenshot from 2020-07-08 14-04-13

### CODE REVIEW

**Comment by elguitar** [comment]
Please rebase on master to start the Travis CI.

**Comment by elguitar** [comment]
Looks good now!
kuva

When screen width is small, the icon still looks a bit wonky.
kuva

**Comment by sjaks** [comment]
@elguitar okay, that was because the icon took its anchor from the button text. Had to adjust the line height instead. Works well now but is not so elegant.

**Comment by elguitar** [comment]
LGTM! Please merge :)

**Pull request merged**
