### PR TITLE
Fix translations strings on cruft page

### PR DESCRIPTION
**Pull request by cr0vy**
Before:
Screenshot from 2019-06-05 11-44-03

After:
Screenshot from 2019-06-05 11-45-33

### CODE REVIEW

**Comment by ottok** [comment]
It still get:
image

You can repeat this by `wp plugin install --activate hello` and changing the code to think `hello` is bad code:
```
diff --git a/lib/cruftplugins-ajax.php b/lib/cruftplugins-ajax.php
index a7aab92..3fedf55 100644
--- a/lib/cruftplugins-ajax.php
+++ b/lib/cruftplugins-ajax.php
@@ -52,6 +52,7 @@ function seravo_ajax_list_cruft_plugins() {
         'wp-client',
         'wp-filebase-pro',
         'miniorange-oauth-client-premium',
+        'hello',
       ),
       'foolish_plugins'  => array(                            //Not malicious but do unwanted things
         'all-in-one-wp-migration',
```

**Comment by ottok** [comment]
Weird that the .pot diff is so huge even though just a few translations have been added. How did you generate the .pot? With `wp i18n make-pot . languages/seravo.pot` or something else?

**Comment by elguitar** [comment]
@ottok [Poedit](https://poedit.net) likes to scramble the .pot-file I think :thinking:

**Comment by ottok** [comment]
Don't use Poedit to generate the pot file. Use WP for it. Use poedit only for editing the .po files.

**Comment by elguitar** [comment]
Ah sorry my mistake!
WP-CLI scrambles them too:
```
petrisalminen@petrisalminen_929307:~/htdocs/wp-content/mu-plugins/seravo-plugin$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
petrisalminen@petrisalminen_929307:~/htdocs/wp-content/mu-plugins/seravo-plugin$ wp i18n make-pot . languages/seravo.pot
Plugin file detected.
Success: POT file successfully generated!
petrisalminen@petrisalminen_929307:~/htdocs/wp-content/mu-plugins/seravo-plugin$ git diff | wc -l
1576
```

**Comment by ottok** [comment]
Weird. Well, let's use the wp i18n scrambled version, hopefully next run of it does not scramble it so much anymore..

**Comment by elguitar** [comment]
I tested this again and the bug that @ottok mentioned is fixed.

I will merge this so that 1.9.9 can be published.

**Pull request merged**
