### PR TITLE
Add 'apply_filters' to $site_info

### PR DESCRIPTION
**Pull request by spktklr**
#### What are the main changes in this PR?
Add 'apply_filters' to $site_info.

##### Why are we doing this? Any context or related work?
Disable seravo_updates via PHP.

#### Where should a reviewer start?
upkeep.php row 133.

#### Manual testing steps?
Not required.

#### Screenshots
Not applicable.

### CODE REVIEW

**Comment by spktklr** [comment]
Perhaps the pull request was a bit hasty and it is not actually possible to disable automatic updates in code, but the setting has to be submitted to Seravo's server?

Is there another way to do this in code?

**Comment by Moppa5** [comment]
@spktklr, Is there a specific reason for you to disable this in code? There is this checkbox on upkeep page if you wish to opt out from Seravo automatic updates (see the screenshot). 
 
Screenshot(2)

**Comment by spktklr** [comment]
@Moppa5 thanks for looking into this. Writing the browser automation to disable this on all sites seems more laborous and non-future-proof than just having adding it at scale in version control.

**Comment by Moppa5** [comment]
@spktklr, Sorry for not getting back to you sooner. As mentioned and noticed earlier this fix is unfortunately not going to work. However, you have good idea here and we will be looking this on our internal implementation as having an effect requires modifications there. Meanwhile we can open an issue about this case here on Seravo Plugin and inform there about the development.

**Pull request closed without merging**
