### PR TITLE
Move zones below the domain

### PR DESCRIPTION
**Pull request by JoosuaKoskinen**
Moves the zones table and the zone editing GUI from below the domains table. Zones are now under the 'view' and 'edit' links of the selected domain.

### CODE REVIEW

**Comment by ottok** [comment]
Please practice using `git rebase -i` to make a nice history, reword commits etc. Also make sure your git repository author settings are correct and the author is always Joosua, not Mainerit.

image

**Comment by JoosuaKoskinen** [comment]
Sure. I noticed the Maineri thing afterwards.

**Comment by JoosuaKoskinen** [comment]
I just made the changes you talked about.

**Comment by ottok** [comment]
Please run `git rebase -i master`

**Pull request merged**
