### PR TITLE
Add the first part of the Seravo Toolbox

### PR DESCRIPTION
**Pull request by cr0vy**
#### What are the main changes in this PR?
This PR will add the first part of the Seravo toolbox.
This first part contains:
- A subpages under "Tools" top level menu 
- Reorganize postboxes to under these the new subpages.

##### Why are we doing this? Any context or related work?
Issue #233

#### Screenshots
tools-menu

toolbox-sitestatus

toolbox-upkeep

toolbox-logs

toolbox-security

toolbox-domains

toolbox-mails

toolbox-development

### CODE REVIEW

**Comment by ottok** [comment]
Nice!

Please review each box before and after the refactoring so that you are sure that you have not accidentally removed/lost some box in the process.

**Comment by ottok** [comment]
These elements are very narrow and thus difficult to read:
image

Could they be made the width of 2 columns maybe?

This view on the other hand is far to wide:
image



Navigation before:
Screenshot from 2019-08-24 19-24-43


Navigation after:
Screenshot from 2019-08-24 19-20-08

**Comment by cr0vy** [comment]
> These elements are very narrow and thus difficult to read:
> image
> 
> Could they be made the width of 2 columns maybe?

Currently postboxes do not support multi columns widget, only single column widget. If we try to set the widget for 50% width of the window in css file, it looks like multi columns view, but it resizes only column 1 width to 50% and doesn't use column 2. This also moves column 4 to the second row.


> This view on the other hand is far to wide:
> image

This looks like the cache includes older shadows.css file and sets column width to 100%. This affects other columns' width and the postboxes use column width.

**Comment by ottok** [comment]
Can the order of boxes be controlled? On my test installation it is a bit odd that two backup related boxes are to the left, then there is update suff in the middle, and again one backup box to the right.
image

Yes, I know I can manually order them around but I don't think many users will do that, and instead the should be set sensible out-of-the-box. Is that possible?

**Comment by cr0vy** [comment]
Yes, it's possible. Function seravo_add_postbox includes $context parameter, which takes values: 'normal', 'side', 'column3', and 'column4'. If the value is 'normal', postbox default location is column-1. If the value is 'side', default location is column-2.

Currently, if you want to reset the postbox order in the site, you need to go to wp db cli from wp-cli.

In `wp db cli`, you can clear the postbox order on every page with SQL command:
`DELETE FROM wp_usermeta WHERE meta_key LIKE 'seravo-postbox-order%';`

The next SQL command clears the postbox order on upkeep_page:
`DELETE FROM wp_usermeta WHERE meta_key = 'seravo-postbox-order_tools_page_upkeep_page';`

**Comment by cr0vy** [comment]
Small update. Currently this PR waiting that we could make a wider postboxes. You will find conservation about wider postboxes from the issue #233. Also, there is two PR which will gonna effect for this pr, full-width postboxes (PR #280) and two column postboxes page (PR #282).

Also, I'm working with wider update for toolbox on dev-seravo-toolbox branch, which is going to replace this current PR changes. This change set include:
- Mails and Domains on the same page
- Tests and updates php files merged into upkeep.php
- Reports, shadows, and optimize-images php files merged into sitestatus.php
- Cruftfiles.php moved to security.php, but this not affet cruftfiles .css, .ajax and .js files.

Pictures from dev-seravo-toolbox with two column postboxes:

Site Status:
site-status


Upkeep:
upkeep


Database:
database


Backups:
backups


Security:
security


Domains:
domains


Logs:
logs

**Comment by cr0vy** [comment]
This latest bunch of commits contain the next things:
    - Mails and domains page merge
    - Updates, tests and shadows files merged into upkeep files
    - Optimize-images, reports and shadows files merged into site status files

**Comment by cr0vy** [comment]
The "Yhteystiedot teknisissä asioissa" link is now linked to the site status page and I removed the "test" link because the "Update Tests" postbox is now on the same page.

It's maybe a good idea to add the "Development" page, which would include the shadows and optimize-images postboxes.

**Comment by l3ku** [comment]
Note that prior to making the next release, the Finnish translations should be skimmed through to ensure that there are none missing, e.g.
Screen Shot 2019-10-08 at 9 58 09
It is however out of the scope of this PR because there seem to be missing translations also from code that has not been modified here.

**Pull request merged**
