### PR TITLE
Fix checking baseline test status from logs

### PR DESCRIPTION
**Pull request by JoosuaKoskinen**
## What are the main changes in this PR?

Fixes incorrect "Test status" on upkeep page.

##### Why are we doing this? Any context or related work?

Issue #307.

#### Manual testing steps?

Using the oneliner from command line is probably the easiest way to test this issue and fix.

### CODE REVIEW

**Comment by ottok** [comment]
This is too complex. No need to run `find` to find just one file?

This ends up in the same file list:
```
$ find /data/log/ -name update.log | xargs echo /data/log/update.log-*
/data/log/update.log-20190113.gz /data/log/update.log-20190121.gz /data/log/update.log-20190127.gz /data/log/update.log-20190203.gz /data/log/update.log-20190211.gz /data/log/update.log-20190217.gz /data/log/update.log-20190225.gz /data/log/update.log-20190303.gz /data/log/update.log-20190311.gz /data/log/update.log-20190317.gz /data/log/update.log-20190325.gz /data/log/update.log-20190331.gz /data/log/update.log-20190408.gz /data/log/update.log-20190414.gz /data/log/update.log-20190421.gz /data/log/update.log-20190429.gz /data/log/update.log-20190512.gz /data/log/update.log-20190519.gz /data/log/update.log-20190526.gz /data/log/update.log-20190616.gz /data/log/update.log-20190707.gz /data/log/update.log-20190728.gz /data/log/update.log-20190811.gz /data/log/update.log-20190825.gz /data/log/update.log-20190908.gz /data/log/update.log-20190922.gz /data/log/update.log-20191006.gz /data/log/update.log-20191020.gz /data/log/update.log-20191103.gz /data/log/update.log-20191117.gz /data/log/update.log-20191124.gz /data/log/update.log-20191208.gz /data/log/update.log-20191215.gz /data/log/update.log-20191229.gz /data/log/update.log-20200112 /data/log/update.log


$ echo /data/log/update.log-* /data/log/update.log
/data/log/update.log-20190113.gz /data/log/update.log-20190121.gz /data/log/update.log-20190127.gz /data/log/update.log-20190203.gz /data/log/update.log-20190211.gz /data/log/update.log-20190217.gz /data/log/update.log-20190225.gz /data/log/update.log-20190303.gz /data/log/update.log-20190311.gz /data/log/update.log-20190317.gz /data/log/update.log-20190325.gz /data/log/update.log-20190331.gz /data/log/update.log-20190408.gz /data/log/update.log-20190414.gz /data/log/update.log-20190421.gz /data/log/update.log-20190429.gz /data/log/update.log-20190512.gz /data/log/update.log-20190519.gz /data/log/update.log-20190526.gz /data/log/update.log-20190616.gz /data/log/update.log-20190707.gz /data/log/update.log-20190728.gz /data/log/update.log-20190811.gz /data/log/update.log-20190825.gz /data/log/update.log-20190908.gz /data/log/update.log-20190922.gz /data/log/update.log-20191006.gz /data/log/update.log-20191020.gz /data/log/update.log-20191103.gz /data/log/update.log-20191117.gz /data/log/update.log-20191124.gz /data/log/update.log-20191208.gz /data/log/update.log-20191215.gz /data/log/update.log-20191229.gz /data/log/update.log-20200112 /data/log/update.log
```

**Comment by JoosuaKoskinen** [comment]
> echo /data/log/update.log-* /data/log/update.log

It's there just in case if update.log doesn't exists. If we could trust that it exists, we probably wouldn't have to parse .gz at all.

**Comment by elguitar** [comment]
I tested both of the solutions.

It is true, that we cannot guarantee that `update.log` exists and using `find` to append it only when it is found could be considered a clean way to achieve the task. 

However, in this situation I think that the readability and the maintainability of the code is a higher priority than the "cleanness" of the code.

The downside of using `update.log-* update.log` is a file-not-found error from `gzip`, which does not matter at all, since only `stderr` is not piped forward.

### Example

I have files update.log, update.log-20180201 and update.log-20170201.gz with the sentence "I am $filename" in them. 

This is the situation where the `update.log` exists:
```
$ php -r "exec('zgrep -h -A1 \"I am\" /home/petrisalminen/test/update.log-* /home/petrisalminen/test/update.log | tail -n1', \$var);var_dump(\$var);"
array(1) {
  [0]=>
  string(15) "I am update.log"
}
```


This is the situation where the `update.log` does not exist:
```
$ php -r "exec('zgrep -h -A1 \"I am\" /home/petrisalminen/test/update.log-* /home/petrisalminen/test/update.log | tail -n1', \$var);var_dump(\$var);"
gzip: /home/petrisalminen/test/update.log.gz: No such file or directory
array(1) {
  [0]=>
  string(24) "I am update.log-20180201"
}
```

The error is printed yes, but it is not getting processed by php.

### Conclusion

I would suggest, that the `update.log-* update.log` form should be used

**Comment by JoosuaKoskinen** [comment]
You are right, the error is ignored. Changed to your suggestion.

**Pull request merged**
