### PR TITLE
Database tools

### PR DESCRIPTION
**Pull request by TeemuSuoranta**
New Database page in Tools:

- Only for admins and can be disabled with filter
- Shows database credentials (if this is too risky, I understand)
- Link to Adminer (needs probably more logic with multisites)
- Combines Search and Replace functionality in same page
- Enhances Search and Replace UI
- Shows database size and each table's size
- Localization for these

I wanted to make Adminer button one-click sign-in but found out that it can't be done by just sending credentials to it with POST request (or at least I failed to do it for an hour). Easiest option would be probably to modify the adminer with extension https://www.adminer.org/en/extension/

But then again, there might be other use cases that need those database credentials like using external DB application to connect to database so even if you can create one-click login, they might still be useful.

Linked issues: https://github.com/Seravo/seravo-plugin/issues/28

screen shot 2017-12-21 at 17 31 50

### CODE REVIEW

**Comment by ottok** [comment]
Impressive! i will try to review this tomorrow.
:champagne:

**Comment by ottok** [comment]
After discussing this internally, we think that exposing the DB password here is not acceptable currently. Could you replace the credentials with a short help text telling how to see the credentials via SSH and wp-list-env ?

Also a short text that remote access to the database is possible via a SSH tunnel.

**Comment by ottok** [comment]
Here is a snippet I use to figure out what is making the wp_postmeta so big (it often is): `select substring(meta_key, 1, 12) as s, count(*) as c from wp_postmeta group by s order by c desc limit 20;`

Should this or something similar be included? I like the fact that you list the size of the database tables. It would be good to show even more info about database contents. Currently no tool (not even Adminer) is has any automagic feature for this type of debugging.

**Comment by TeemuSuoranta** [comment]
I'll try to make the commit for removing credentials out today. I understand there are many risks for just showing them and it might be better to not show them even if it makes developers take a few extra steps.

For debugging slow database maybe we could separate plain size and debuggin to different sections. The "Database size" could run always but maybe the "Debug database" could run after user has clicked a button.

I'd separate the two because the debugging will probably grow to have many more tests in future. In addition to post_meta the options table could be one thing to check as well. I know one case at least when WPML stuffed one option value with many MB of stuff by faulty string registration.

**Comment by TeemuSuoranta** [comment]
Credentials are now removed and instructions added. I renamed "Database info" already to "Database size" ready for future debug tools.

screen shot 2017-12-22 at 14 56 01

**Comment by ottok** [comment]
What tool are you using to generate the .pot file? In your commit you remove all the plugin desc fields from the end. You new fi.po also introduces many fuzzy lines. If you use the wp-makepot in our Vagrant image, you will automatically get perfect WordPress standard pot files.

**Comment by TeemuSuoranta** [comment]
I was using Poedit that has the ability to generate .pot files as well as edit translations. I wasn't even aware of wp-makepot command as it's not really documented in docs. When I regenerated the .pot with that command as wp-plugin the missing info returned. I also noticed a few warnings in existing translations for minor inconsistencies with translations like original string ending with space and translation not. All this is fixed now.

**Comment by ottok** [comment]
Thanks!

**Comment by ottok** [comment]
You can deploy this with `wp-seravo-plugin-update --dev` on your sites where you want to see it in action.

**Pull request merged**
