### PR TITLE
Update updates-tool layout to WordPress layout

### PR DESCRIPTION
**Pull request by nasusa**
- Update updates-tool layout to WordPress layout (postboxes)
- Show technical contact emails in buttons
- Add updates.css -file
- Make layout mobile responsive

I did accidentally delete my latest pr, but luckily I had these files saved to my computer.

image

### CODE REVIEW

**Comment by nasusa** [comment]
Done!

**Comment by l3ku** [comment]
Tested this, and found a bug: each email is added two times to the list when hitting the enter key instead of pressing the "Add button":
screen shot 2018-06-12 at 15 47 01
After hitting enter:
screen shot 2018-06-12 at 15 47 50

Also, please rebase this branch on master as this branch is out-of-date with the base branch.

**Comment by nasusa** [comment]
I added custom error to email validation and did style to it, also fixed bugs.

There was also another bug; when you added email and clicked enter, form saved settings at the same time. I added `event.preventDefault();` and i took away `"type="submit"` from add-button.

**Comment by l3ku** [comment]
The new custom error looks very nice 👍

**Pull request merged**
