### PR TITLE
Travis CI: Actually fail if php syntax checking fails

### PR DESCRIPTION
**Pull request by onnimonni**
Current implementation returns true always.

### CODE REVIEW

**Comment by ottok** [comment]
Thanks!

Next time squash your commits. Fixes of fixes within the PR are not relevant for the project history.

**Comment by ottok** [comment]
Similar check is done in https://github.com/Seravo/wordpress/blob/master/scripts/hooks/pre-commit#L69, but the result is evaluated line per line and not just the last line of a list, so that pre-commit hook does not need updating.

**Comment by onnimonni** [comment]
You can squash the commits in github too :)! More information here: https://github.com/blog/2141-squash-your-commits

**Comment by ottok** [comment]
Yes, that is what I did.

**Pull request merged**
