### PR TITLE
GoAccess reports issue Closes #127

### LINKED ISSUE #127: GoAccess' reports cannot be reached
On the Reports page of the plugin, there is the http requests report tool.
The links to the GoAccess' reports lead nowhere. Probably a typo in the links.

### PR DESCRIPTION
**Pull request by nasusa**
GoAccess' reports couldnt be reached. There was extra quotation marks, now links should work.

Closes #127 .

### CODE REVIEW

**Comment by nasusa** [comment]
Woops didn't even know there was a link too, fixed now 👍

**Comment by elguitar** [comment]
Seems good! Could you rebase on top of master and force-push to your branch?

**Comment by nasusa** [comment]
done'd

**Comment by elguitar** [comment]
Great!!!!! :+1:

**Pull request merged**
