### PR TITLE
Parse PHP versions from local file

### PR DESCRIPTION
**Pull request by JoosuaKoskinen**
Parse available, recommended and EOL versions from /etc/php/versions.

The code is mostly same as in https://github.com/Seravo/seravo-plugin/pull/653 so the review from there should so OK here too. The EOL notification should be reviewed again.

### CODE REVIEW

**Comment by Wiljami** [comment]
Tested this on a fresh site. Wp-admin panel would end up just displaying only:
```
"7.3"
```
on the screen (it being the only source code as well) with this seravo-plugin change.

**Comment by Wiljami** [comment]
Tested this on a fresh site. Wp-admin panel would end up just displaying only:
```
"7.3"
```
on the screen (it being the only source code as well) with this seravo-plugin change.

**Comment by JoosuaKoskinen** [comment]
> Tested this on a fresh site. Wp-admin panel would end up just displaying only:
> 
> ```
> "7.3"
> ```
> 
> on the screen (it being the only source code as well) with this seravo-plugin change.

Forgot some debug code, fixed now.

**Review by Wiljami — DISMISSED** [review]
Tested.

`get_recommended_php_version` returns 8.0 and `get_eol_php_version` returns 7.3

Which looks good to me and with the above fix, the site is no longer broken due to debug.

**Comment by JoosuaKoskinen** [comment]
@Wiljami can you approve again. Nothing in code has changed, just rebased.

**Pull request merged**
