### PR TITLE
Introduce PHPStan

### LINKED ISSUE #541: [joy request] Welcome to beneficial world of static analysis!
I'm happy that you joined the users of PHPStan!

Please let me send a PR.

### PR DESCRIPTION
**Pull request by szepeviktor**
#### What are the main changes in this PR?

Introduce the seed of robust operation.
This says it all.

Closes #541

### CODE REVIEW

**Comment by szepeviktor** [comment]
Please start on Level 0 `vendor/bin/phpstan analyse -l 0`

Inner named functions are really good poisons. 🧪 Please remove them once and for all.

**Comment by elguitar** [comment]
Thank you very much for your contribution! We are happy to try PHPStan out :)

**Comment by JoosuaKoskinen** [comment]
We couldn't get this to work:
```
vendor/bin/phpstan analyse -l 0                        
Note: Using configuration file /home/joosua/seravo/seravo-plugin/phpstan.neon.

In Resolver.php line 110:
                                                                                               
  Service '0236': Class PHPStan\WordPress\IsWpErrorFunctionTypeSpecifyingExtension not found.  
                                                                                               

analyse [--paths-file PATHS-FILE] [-c|--configuration CONFIGURATION] [-l|--level LEVEL] [--no-progress] [--debug] [-a|--autoload-file AUTOLOAD-FILE] [--error-format ERROR-FORMAT] [--generate-baseline [GENERATE-BASELINE]] [--memory-limit MEMORY-LIMIT] [--xdebug] [--fix] [--watch] [--pro] [--] [<paths>...]
```

Is this something you can help us with?

**Comment by szepeviktor** [comment]
@JoosuaKoskinen I think this

```json
"post-install-cmd": [
    "git restore vendor/"
],
```

Removes some of the packages.

Try `composer update --no-scripts`

**Comment by JoosuaKoskinen** [comment]
> @JoosuaKoskinen I think this
> 
> ```json
> "post-install-cmd": [
>     "git restore vendor/"
> ],
> ```
> 
> removes some of the packages.
> 
> Try `composer update --no-scripts`

Thanks for noticing that!

I think we should wait until the refactoring process, which is currently in process, gets done so we can get rid of the inner named functions etc first.

**Comment by szepeviktor** [comment]
> Thanks for noticing that!

❤️ 

I've heard a fairy tale.

_Once upon a time there were inner named functions,
They've became private methods._

**Comment by JoosuaKoskinen** [comment]
These commits were rebased and merged on https://github.com/Seravo/seravo-plugin/pull/593.

**Comment by szepeviktor** [comment]
Thank you.

**Pull request closed without merging**
